### ISSUE TITLE
WEBP Plugin Crashes Photoshop 2020

### ISSUE THREAD

**Issue by thoughtcastapp** [webmproject/WebPShop#13]
Hi, I have PS 2020 installed on my mac running catalina. When I open PS, it asks if I want to load plugins not installed by adobe and, when I click yes, it crashes photoshop. Here's the log it generated on crash, hope this helps (it's a shame this isn't built into photoshop natively):

Process:               Adobe Photoshop 2020 [37398]
Path:                  /Volumes/VOLUME/Applications/Adobe Photoshop 2020/Adobe Photoshop 2020.app/Contents/MacOS/Adobe Photoshop 2020
Identifier:            com.adobe.Photoshop
Version:               21.0.1 (21.0.1.47)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Adobe Photoshop 2020 [37398]
User ID:               501

Date/Time:             2020-07-06 13:57:27.849 -0700
OS Version:            Mac OS X 10.15.5 (19F101)
Report Version:        12
Anonymous UUID:        DA030EAF-0155-ABB9-A1FC-570C8BF974E3

Sleep/Wake UUID:       DFD244C9-FC0C-4D5A-82E4-DA2AFF3DBF6D

Time Awake Since Boot: 440000 seconds
Time Since Wake:       440000 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [37398]

**Comment by y-guyon** [comment]
Thanks for the report. I cannot deduce from the log that the issue comes from WebPShop but here are a few leads to try:

- Run the `xattr` command as described [here](https://github.com/webmproject/WebPShop#installation).
- Update Photoshop to its latest version (21.2).
- Remove all plugins from all folders and try putting WebPShop back in one of these as described [here](https://github.com/webmproject/WebPShop#troubleshooting).
