### ISSUE TITLE
webp not properly handling color profile

### ISSUE THREAD

**Issue by Chillstice** [webmproject/WebPShop#16]
I saw mention of color shifts in #4 , but I'm not experiencing the same thing. This has to do with embedded color profiles. I use a color calibrated monitor and I convert all my photographs to `sRGB IEC61966-2.1` so that they appear as close to the original colors as possible across as many monitors and image viewers as possible. Most modern web browsers now support color management and will use the embedded profile to properly display the tagged images. 

The issue is that even though the `keep color profile` option is checked when saving to webp, the resulting image file isn't tagged or doesn't have the color profile embedded. 

Here's what Bridge reports:
![image](https://user-images.githubusercontent.com/1124121/89692872-12492b80-d8ca-11ea-966c-a3a1cb699e18.png)

When using color managed programs like ImageGlass or Bridge, the colors shift in the webp vs the original jpeg because the program doesn't know what the embedded profile is supposed to be or it's missing entirely. There is an option to force untagged images in a web browser to always assume srgb, but most people don't have that set.

**Comment by Chillstice** [comment]
Great work on the plugin though, it works great otherwise. It's just this one quirk is preventing me from switching to webp for all the images on my website.

**Comment by y-guyon** [comment]
I did not manage to reproduce the issue by opening a JPG image containing a `sRGB IEC61966-2.1` color profile, using "Save as..." to convert it to WebP and checking "Keep Color Profile". The "Preview" feature shows the change in final size. I am using WebPShop 0.3.0, Photoshop 21.1.2 x64 on Windows Server 2016. I use Chrome to view the images and [ImageMagick `identify -verbose`](https://imagemagick.org/script/identify.php) to check the ICC metadata.
Could you provide your OS, Photoshop and WebPShop versions, the exact steps taken and the source+converted images?

A few notes:
- I am surprised that Adobe Bridge supports WebP because Photoshop does not natively.
- Some software decode WebP images fine but do not handle color profiles correctly.
- You might want to "apply" and discard the color profile before saving to WebP; you would decrease the file size and increase compatibility, although your use case might not fit.
- GIMP can encode WebP natively but I am not sure that color profiles are correctly handled. It might be worth it to check it out.
- Using the [`cwebp` binary](https://developers.google.com/speed/webp/docs/cwebp) is also an option with the `-metadata` flag.
- When you say "tagged", is that some EXIF or XMP metadata? Did you try including those?

**Comment by Chillstice** [comment]
I also noticed the file size change, but I can't help but notice that the colors shift in the same way they would if they were untagged and just displaying with full saturation depending on the gamut of the monitor.  

I'm using WebPShop 0.3.0, Photoshop 21.2.1 x64, Windows 10 Pro 10.0.18363
And like I said I'm using both Bridge and ImageGlass to view images since they both support embedded color profiles and 
support converting to the monitor's profile. This means the srgb gamut is clamped on monitors that are capable of showing more saturated colors (most browsers now support this too, although it needs to be enabled on Firefox [https://cameratico.com/guides/web-browser-color-management-guide/](https://cameratico.com/guides/web-browser-color-management-guide/))

I decided to test with an image that has an intentionally fucked icc color profile to see if it would embed and be tagged properly. The image works by appearing normal when the colors are converted properly, but if the color profile doesn't work it just ends up looking super purple. Surprisingly, using WebPShop to convert it to Webp works and the colors look normal, but when comparing it to the srgb reference version, there is still a discrepancy. I think for whatever reason the image viewers are handling the file differently because it might be missing the color profile tag. I don't know exactly which part of the metadata handles the profile tag, but Bridge reports it as `untagged` even if the EXIF and XMP metadata is enabled when saving.

For whatever reason I assumed that WebPShop didn't embed the color profile at all, but this test proves that it's working, but image viewers are treating it as `untagged` so it's not as bad as I thought. I'll be converting all my images here shortly.

![image](https://user-images.githubusercontent.com/1124121/89828565-74966c00-db16-11ea-8184-20d4e92e193d.png)

Also here's the WhackedRGB test image stuff: [http://www.gballard.net/photoshop/pdi_download/](http://www.gballard.net/photoshop/pdi_download/)

**Comment by delthas** [comment]
Images not tagged with a color profile are [specified to default to sRGB](https://drafts.csswg.org/css-color-4/#untagged) so this should not be an issue if you're trying to apply the sRGB profile anyway.
