### ISSUE TITLE
Open and Save Options Missing

### ISSUE THREAD

**Issue by cynetix** [webmproject/WebPShop#2]
[OBSERVED BEHAVIOR]

- The WebP file option is missing from both the open and save dialogues.

[EXPECTED BEHAVIOR]

- WebP should be available in the drop-down list.

[TROUBLESHOOTING STEPS TAKEN]

- Uninstalled plugin version 2.1 and reinstalled 2.1.
- Uninstalled plugin version 2.1 and installed 2.0.
- Confirmed in 8bit RGB colour mode
- Checked plugin location was correct (C:\Program Files\Adobe\Adobe Photoshop CC 2019\Plug-ins) - Also contains other plugins that work.

[SYSTEM INFO]

OS: Windows 10 version 1903 x64
App: Adobe Photoshop Version: 20.0.5 x64

**Comment by y-guyon** [comment]
Thanks for the report.

Do you have any related error message when opening Photoshop?
What is the language of your Windows and Photoshop installation? WebPShop is currently only in English and I don't know if it would be recognized with another locale.

Could you check whether it's listed in "Help > About" please? I guess not since it's missing from the Open dialogue.

Another thing to verify is the architecture of the plug-in binary matching the Photoshop one (x64 here).

What are the steps taken for (un)installation exactly? It should only be (re)moving the "[WebPShop.8bi](https://github.com/webmproject/WebPShop/tree/master/bin/WebPShop_0_2_1_Win_x64)" file in the "C:\Program Files\Adobe\Adobe Photoshop CC 2019\Plug-ins" directory, after closing Photoshop. Also restarting Windows might help sometimes.

**Comment by cynetix** [comment]
Thank you for your speedy response.

Uninstallation was achieved by removing the plug-in from the plug-in directory and restarting Photoshop. Installation was that in reverse.

I have tried to drop Photoshop down to 20.0.4, as I noted a previous issue report had that version listed and working, and it was the same problem.

The plug-in is not listed in "Help > About", but others that are in the same plug-in directory are.

Can you explain what you want me to do here please - note I assume a url is missing?
> Another thing to verify is the architecture of the plug-in binary matching the Photoshop one (x64 here).

I am going to try and restart Windows now.

**Comment by y-guyon** [comment]
I meant "here" as "in the current case", not as a link. [Here's the direct link for WebPShop 0.2.1 Windows Photoshop x64 if needed.](https://github.com/webmproject/WebPShop/releases/download/v0.2.1/WebPShop_0_2_1_Win_x64.8bi)

Also you did not mention in what language Windows and Photoshop were set up.

**Comment by cynetix** [comment]
Apologies, it's English International.

A PC restart didn't help.

However, using the version you linked to here worked, I can only apologise I must be a complete idiot, I have no idea what I had done!

I can confirm plug-in now appears to be working perfectly, thank you kind sir! :D

**Comment by y-guyon** [comment]
I'm glad that it works :) You probably used the x86 binary instead of the x64 one; I'm afraid Photoshop is not very talkative when it encounters a problem with a plug-in.

Don't forget to close this issue if it's all sorted out.

**Comment by cynetix** [comment]
Many thanks!
