### ISSUE TITLE
Photoshop path

### ISSUE THREAD

**Issue by haskellromero** [webmproject/WebPShop#24]
The plugin does not export the XMP data correctly, specifically the photoshop path, which is possible in any JPEG or JPEG2000 file, it would be nice to have that option.

![image](https://user-images.githubusercontent.com/22428538/102977236-53805780-44c8-11eb-8902-57476d8e3ded.png)

![image](https://user-images.githubusercontent.com/22428538/102978643-6eec6200-44ca-11eb-8e54-64ac5446a186.png)

**Comment by y-guyon** [comment]
Thank you for the report. I did not manage to keep a Path through a JPEG (`Save as...`/`Export as...`) but it worked through a JPEG2000 (`Save as...`). Could you provide the steps for JPEG?

Anyway I do not know what kind of metadata it is stored into in JPEG2000 but it does not seem to be XMP nor EXIF, because it works when I enable `Include Metadata` but disable `JPEG 2000 XML`, `XMP` and `EXIF`. It does not work when I disable `Include Metadata`. ICC, XMP and EXIF are the only metadata chunks that can be stored in the WebP format so I doubt there is a way of keeping the Adobe Photoshop Paths data. Did you try with other plugins such as [fnordware AdobeWebM](https://github.com/fnordware/AdobeWebM) or [telegraphics WebPFormat](http://www.telegraphics.com.au/sw/product/WebPFormat)?

You can try changing the way XMP metadata is exported in [WebPShopEncodeUtils.cpp](https://github.com/webmproject/WebPShop/blob/67fbb3ee65ce0445b8e5dd77b1154fe6ac6cdd84/common/WebPShopEncodeUtils.cpp#L200) and/or with [XMPRead and XMPWrite properties](https://github.com/webmproject/WebPShop/blob/67fbb3ee65ce0445b8e5dd77b1154fe6ac6cdd84/common/WebPShop.r#L87) if you like.

**Comment by haskellromero** [comment]
Thank you very much for the info, I will try the plugins you mentioned to me and finally the option of WebPShopEncodeUtils.cpp

I've been looking for space-saving options in a new workflow I'm testing, webp seemed like the ideal format except for that little clipping path detail.
