### ISSUE TITLE
Noticeable colour shift when saving to webp from jpg

### ISSUE THREAD

**Issue by fyreflyt** [webmproject/WebPShop#4]
I've discovered an issue with both this plugin and Telegraphics plugin in Photoshop CC 2020. 

The jpg maintains the vibrancy of the product's copper colour. When I save to webp, the colours become noticeably desaturated. Looking more like a dull gold, rather than bright copper. 

I've tried several options, all show this same result. The zip contains the source jpg and my webp result.

[Swatches-jpg-webp.zip](https://github.com/webmproject/WebPShop/files/3880599/Swatches-jpg-webp.zip)

**Comment by y-guyon** [comment]
The "swatch-copper.webp" you sent has the same XMP metadata as the .jpg one, hence the colors should be displayed in the same way (it is in my Chrome version). You probably created this one with the Telegraphics plugin because the WebPShop one does not currently handle metadata.

I suggest applying and stripping the metadata because it might not be handled the same way everywhere. For this image it's possible directly in Photoshop:

1. _Export_ > _Export As..._
2. Format: _PNG_, Metadata: _None_, Color Space: _Convert to sRGB_ but do not _Embed Color Profile_
3. Open the newly created .png file and _Save As..._ > _WebP_

[swatch-copper-no-xmp.webp.zip](https://github.com/webmproject/WebPShop/files/3885725/swatch-copper-no-xmp.webp.zip)

**Comment by y-guyon** [comment]
Fixed in e5e16782b87ac90d690361251d900187d9e52d3e.
