### ISSUE TITLE
WEBP 16 & 32bit save options from .EXR, .PNG, .JPG not showing 

### ISSUE THREAD

**Issue by sylicongames** [webmproject/WebPShop#44]
Could someone kindly advise on the steps needed to convert an image from the above mentioned formats into .WEBP 16/32bit? 
Source image is RGB 32bit, ive tried several formats. 
thanks in advance

EDIT : Im not having success with PS 22.2 , 23.0.2. Ive tried the Save a Copy, stil no dice. This is on Win10 environment.

**Comment by y-guyon** [comment]
The WebP format only stores a precision of 8 bits per pixel per channel. \
In [WebPShop 0.4.0](https://github.com/webmproject/WebPShop/releases/tag/v0.4.0), I added 16/32 bits export for convenience only. Internally it converts to 8 bits before saving to the actual WebP file. \
There should also be a prompt if the color mode is not handled, rather than hiding the WebP format from the list of output extensions.

On top of the Photoshop and Windows versions you provided, could you also give the WebPShop version, and a minimal source image that reproduces the issue?
