### ISSUE TITLE
Webp animation glitchy with frames out of order.

### ISSUE THREAD

**Issue by galaxy-nomad** [webmproject/WebPShop#50]
Hello I tried to create a smooth animation of spinning car wheels in photoshop. Unfortunately due to memory and quality issues I cannot use PhotoShops native export GIF feature. That said when I preview the GIF animation using the timeline in Photoshop it is nice and smooth. 

When I export the animation to webp it is not only choppy but it glitches out seeming to display frames in the incorrect order despite my meticulous effort to ensure that each layer was named appropriately and ordered sequentially. Also the loop feature fails altogether with the image completing maybe one or two stuttering glitchy loops and then grinding to a halt. I'm viewing the file using Brave Browser. Can you help me to achieve a world class animated webp file using your excellent plugin?

**Comment by mobiland10** [comment]
...

**Comment by galaxy-nomad** [comment]
I have found a workaround of sorts. It turns out if I reduce the size of my GIF to 500 pixels I can get a nice usable export. Maybe there is a size cap for webp animations? Or maybe I'm hitting my memory ceiling in PhotoShop with larger sizes and that's causing the issue.

**Comment by y-guyon** [comment]
Thanks for your report. Could you provide the original and WebP animations? It is difficult to identify the issue without.

There is a fairly high size cap for webp animations: [16383×16383 pixels](https://developers.google.com/speed/webp/faq#what_is_the_maximum_size_a_webp_image_can_be) per frame. However having large dimensions with a high framerate requires a lot of computational resources at rendering. What is your display device? Did you try viewing your animation on a high-end desktop or laptop with a recent version of Chrome?

Depending on your use case, if you need to display an animation with large dimensions and a high framerate (for it to be smooth), you may want to use a video instead of an image. WebP animations were designed to be lightweight animated images with a slow framerate and reasonable dimensions.

**Comment by galaxy-nomad** [comment]
Thanks for your response and information. If I decide to revisit the webp format I will keep your suggestions in mind.
