### ISSUE TITLE
PSD Export as WebP Dialogue with MetaData and Options

### ISSUE THREAD

**Issue by ratzrattillo** [webmproject/WebPShop#7]
The Photoshop plugin you created is really great! Thumbs up for your work!

It would be a great addition to allow a direct export from PSD to WebP. Please consider including this feature, as it would also greatly improve the Workflows of Photographers and Graphic Designers.
This functionality could be integrated in the "Export..."-Dialogue. The "Export..."-Dialogue should also include the parameters supported nativly by the cwebp application (Resizing, Including all XMP-Metadata, Quality-Settings and so on).
This would be the next step to make WebP more attractive for future use and acceptance among the community!

Keep up your good work!

**Comment by y-guyon** [comment]
Thank you!

Although I agree it would be best-suited, it seems to be impossible to modify the native Photoshop "Export..." window through the SDK. Using the `File>Import>WebP` and `File>Export>WebP` submenus would be possible thanks to the **Import** and **Export Module** but it would require one of each, instead of a single **Format Module**. It is also written in the Photoshop SDK documentation that "[Export plug-in modules] can also be used to save images in unsupported or compressed file formats, although File Format modules often are better suited for this purpose". Based on that, it appeared simpler to go with the **Format plug-in** that handles the `Open` and `Save` commands and keeps the same Photoshop file selection dialog.

Adding more parameters to the "WebP settings" dialog (shown after `Save`) is planned but probably not Resizing as this can be handled directly by Photoshop.

**Comment by ratzrattillo** [comment]
Sounds really goof!

I can follow your arguments. What about the inclusion of metadata in the exported WebP files? When exporting JPEGs Matadata like Author- Copyright- and Tag-Inforamtions are integrated. Are there plans for including this metadata also in WebP files? That would be an important feature too, to improve e.g. SEO on websites.
The cwebp.exe already seems to contain this feature. I guess it could facilitate an integration into this plugin.

Greetings!

**Comment by y-guyon** [comment]
Yes, it is planned to add a feature to WebPShop for exporting metadata such as EXIF, XMP and ICC profile.

**Comment by y-guyon** [comment]
Fixed in e5e16782b87ac90d690361251d900187d9e52d3e.
